name: Rust

on:
  push:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock", ".github/**/*.yml"]
  pull_request:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock"]

jobs:        

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos-action      
        uses: crate-ci/typos@v1.28.4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-cache"
      - run: cargo hack check --feature-powerset

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-cache"
      - run: cargo hack clippy --feature-powerset -- --deny warnings

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-cache"
      - run: cargo test --all-features

